name: Convert M3U to TXT

on:
  schedule:
  - cron: '02 0,9 * * *'  #5-7-9-11-13-15-17-19-21-23 》02分&&&
  workflow_dispatch:
    分支:
      - master
      
      

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install m3u8 requests

    - name: Run Python Script
      run: python cc.py

    - name: Upload txt file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: tv.txt
        path: ./tv.txt

    - name: Commit and push changes
      run: |
       git config --global user.email "actions@github.com"
       git config --global user.name "GitHub Actions"
       git add tv.txt
       git commit -m "Update tv.txt [skip ci]"
       git push
