
name: Auto Update IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install m3u8 requests

      - name: Run Update IPTV
        run: |
            python  cc.py

    - name: Upload txt file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: iptv.txt
        path: ./iptv.txt
        
      - name: Commit results
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            if [ -n "$(git status --porcelain)" ]; then
            git add  *.txt #*.m3u
            git commit -am "Automatic update"
            git push
            else
              echo "No changes detected, skipping commit."
            fi
