name: Auto Update IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  iptv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install m3u8 requests

       - name: Run Update IPTV
        run: |
            python  cc.py

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto Update IPTV
          branch: main
          push_options: '--force'
  
