
name: Auto Update IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  iptv:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install m3u8 requests

      - name: Run Update IPTV
        run: |
            python  cc.py

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto Update IPTV
          branch: main
          push_options: '--force'

